<?php

return [
    // Default rewards for Level 1 Gacha System
    'default_rewards' => [
        // A. Emotional & Relationship-Oriented (1-10)
        [
            'id' => 1,
            'category' => 'emotional',
            'title' => 'Voice Note Manis',
            'description' => 'Kirim voice note 1 menit berisi pesan manis (bebas tema)',
            'icon' => '🎤',
            'color' => 'rose',
        ],
        [
            'id' => 2,
            'category' => 'emotional',
            'title' => '5 Hal yang Disyukuri',
            'description' => 'Tulis 5 hal yang kamu syukuri tentang pasangan',
            'icon' => '💝',
            'color' => 'pink',
        ],
        [
            'id' => 3,
            'category' => 'emotional',
            'title' => 'Good Morning/Night Custom',
            'description' => 'Kirim "good morning" atau "good night" custom selama 3 hari',
            'icon' => '🌅',
            'color' => 'amber',
        ],
        [
            'id' => 4,
            'category' => 'emotional',
            'title' => 'Janji Tidak Marah',
            'description' => 'Janji tidak marah selama 24 jam',
            'icon' => '😇',
            'color' => 'blue',
        ],
        [
            'id' => 5,
            'category' => 'emotional',
            'title' => 'Kenangan Favorit',
            'description' => 'Ceritakan kenangan favorit kalian (min. 1 paragraf)',
            'icon' => '📖',
            'color' => 'purple',
        ],
        [
            'id' => 6,
            'category' => 'emotional',
            'title' => 'Lagu Spesial',
            'description' => 'Kirim satu lagu + alasan kenapa lagu itu cocok',
            'icon' => '🎵',
            'color' => 'indigo',
        ],
        [
            'id' => 7,
            'category' => 'emotional',
            'title' => 'Video Thank You',
            'description' => 'Video singkat (≤30 detik) bilang "thank you"',
            'icon' => '🎬',
            'color' => 'teal',
        ],
        [
            'id' => 8,
            'category' => 'emotional',
            'title' => 'Pujian Jujur',
            'description' => 'Pujian jujur tanpa bercanda',
            'icon' => '💖',
            'color' => 'rose',
        ],
        [
            'id' => 9,
            'category' => 'emotional',
            'title' => 'Kata-kata Lembut',
            'description' => 'Satu hari full pakai kata-kata lembut',
            'icon' => '🌸',
            'color' => 'pink',
        ],
        [
            'id' => 10,
            'category' => 'emotional',
            'title' => 'Foto Lama Bercerita',
            'description' => 'Kirim satu foto lama yang punya cerita',
            'icon' => '📷',
            'color' => 'amber',
        ],

        // B. Action / Challenge Ringan (11-20)
        [
            'id' => 11,
            'category' => 'action',
            'title' => 'Topik Ngobrol',
            'description' => 'Menentukan topik ngobrol malam ini',
            'icon' => '💬',
            'color' => 'blue',
        ],
        [
            'id' => 12,
            'category' => 'action',
            'title' => 'Pilih Film',
            'description' => 'Menentukan film untuk ditonton bareng',
            'icon' => '🎥',
            'color' => 'purple',
        ],
        [
            'id' => 13,
            'category' => 'action',
            'title' => 'Virtual Date',
            'description' => 'Menentukan agenda virtual date berikutnya',
            'icon' => '📅',
            'color' => 'indigo',
        ],
        [
            'id' => 14,
            'category' => 'action',
            'title' => 'Truth Question',
            'description' => 'Truth question (tanpa boleh skip)',
            'icon' => '❓',
            'color' => 'teal',
        ],
        [
            'id' => 15,
            'category' => 'action',
            'title' => 'Dare Ringan',
            'description' => 'Dare ringan (aman & sopan)',
            'icon' => '🎯',
            'color' => 'rose',
        ],
        [
            'id' => 16,
            'category' => 'action',
            'title' => 'Mengalah Sekali',
            'description' => 'Mengalah satu kali di debat berikutnya',
            'icon' => '🤝',
            'color' => 'pink',
        ],
        [
            'id' => 17,
            'category' => 'action',
            'title' => 'Pertanyaan Random',
            'description' => 'Menjawab satu pertanyaan random dari sistem',
            'icon' => '🎲',
            'color' => 'amber',
        ],
        [
            'id' => 18,
            'category' => 'action',
            'title' => 'Cerita Jujur',
            'description' => 'Cerita jujur tentang hal yang sedang dipikirkan',
            'icon' => '💭',
            'color' => 'blue',
        ],
        [
            'id' => 19,
            'category' => 'action',
            'title' => 'Meme Hubungan',
            'description' => 'Kirim meme yang menggambarkan hubungan kalian',
            'icon' => '😂',
            'color' => 'purple',
        ],
        [
            'id' => 20,
            'category' => 'action',
            'title' => 'Tema Playlist',
            'description' => 'Menentukan tema playlist bersama',
            'icon' => '🎧',
            'color' => 'indigo',
        ],

        // C. Privilege & Fun Rules (21-30)
        [
            'id' => 21,
            'category' => 'privilege',
            'title' => 'Emotikon Wajib',
            'description' => 'Bebas pilih emotikon yang wajib dibalas hari ini',
            'icon' => '😊',
            'color' => 'teal',
        ],
        [
            'id' => 22,
            'category' => 'privilege',
            'title' => 'No Late Reply',
            'description' => '"No late reply" privilege selama 1 hari',
            'icon' => '⚡',
            'color' => 'rose',
        ],
        [
            'id' => 23,
            'category' => 'privilege',
            'title' => 'Free Pass',
            'description' => 'Free pass (1 kali, bebas minta apa saja yang wajar)',
            'icon' => '🎫',
            'color' => 'pink',
        ],
        [
            'id' => 24,
            'category' => 'privilege',
            'title' => 'Akhiri Chat',
            'description' => 'Bebas mengakhiri chat terakhir hari ini',
            'icon' => '💤',
            'color' => 'amber',
        ],
        [
            'id' => 25,
            'category' => 'privilege',
            'title' => 'Nama Panggilan',
            'description' => 'Menentukan nama panggilan spesial sementara',
            'icon' => '✨',
            'color' => 'blue',
        ],
        [
            'id' => 26,
            'category' => 'privilege',
            'title' => 'Spam Pass',
            'description' => 'Bebas spam 3 pesan tanpa direspon balik',
            'icon' => '💨',
            'color' => 'purple',
        ],
        [
            'id' => 27,
            'category' => 'privilege',
            'title' => 'Penjelasan Detail',
            'description' => 'Bebas minta dijelasin satu hal secara detail',
            'icon' => '📝',
            'color' => 'indigo',
        ],
        [
            'id' => 28,
            'category' => 'privilege',
            'title' => 'Cerita Sebelum Tidur',
            'description' => 'Bebas minta cerita sebelum tidur',
            'icon' => '🌙',
            'color' => 'teal',
        ],
        [
            'id' => 29,
            'category' => 'privilege',
            'title' => 'Screenshot Aktivitas',
            'description' => 'Bebas minta screenshot aktivitas (yang sopan)',
            'icon' => '📱',
            'color' => 'rose',
        ],
        [
            'id' => 30,
            'category' => 'privilege',
            'title' => 'Surprise Reward',
            'description' => 'Surprise reward (di-random ulang dari list)',
            'icon' => '🎁',
            'color' => 'pink',
        ],
    ],
];
