-- =====================================================
-- 004. ADD SPACE_ID TO NOTIFICATIONS
-- =====================================================
-- This migration is now included in 00001_full_setup.sql
-- All changes (space_id column, index, policies, realtime) are already applied.
-- Kept as empty migration for version tracking.
