-- =====================================================
-- Migration: Add invite_code to spaces and source to space_invitations
-- =====================================================
-- This migration is now included in 00001_full_setup.sql
-- All changes (invite_code, source column, policies, indexes) are already applied.
-- Kept as empty migration for version tracking.
